# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QTableWidgetItem, QTableWidget, QDialog
import os.path
import json

from qgis.core import QgsVectorLayer

from .assistant_liste_dialog import ListeDialog
# from .select_all_layer import *
from .liste_dlg import *

TITRE = "Assistant liste v0.0.1"

class AssistantListe:
    def __init__(self, iface):
        self.iface = iface
        # liste des fichiers json trouvé dans le dossier LISTES
        self.fichiers_json = None
        self.dlg = None
        self.nb_elements = None

        # instanciation de la class DialogListe
        self.dlg_liste = DialogListe(self)

        self.dossier_listes = os.path.join(os.path.dirname(__file__), "LISTES")
        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def inittablewidget(self):
        self.dlg.tableWidget.setColumnCount(2)
        self.dlg.tableWidget.setHorizontalHeaderLabels(["Listes", "Nb entités"])
        self.dlg.tableWidget.setColumnWidth(0, 190)
        self.dlg.tableWidget.setColumnWidth(1, 60)
        self.dlg.tableWidget.verticalHeader().setDefaultSectionSize(10)
        self.dlg.tableWidget.verticalHeader().setVisible(False)
        # Rendre toutes les cellules non éditables
        self.dlg.tableWidget.setEditTriggers(QTableWidget.NoEditTriggers)

    def creerliste(self):
        nom = self.dlg.lineEditNewList.text()
        if nom == "":
            return
        item_nom = QTableWidgetItem(nom)

        item_nb = QTableWidgetItem("0")
        # rendre non sélectionnable
        item_nb.setFlags(item_nb.flags() & ~Qt.ItemIsSelectable)

        item_nb.setTextAlignment(Qt.AlignCenter)

        nbligne = self.dlg.tableWidget.rowCount()
        self.dlg.tableWidget.insertRow(nbligne)
        self.dlg.tableWidget.setItem(nbligne, 0, item_nom)
        self.dlg.tableWidget.setItem(nbligne, 1, item_nb)
        self.dlg.lineEditNewList.clear()

        # creer un json vide mais avec la structure
        self.initjsonlist(nom)

    def get_dico_from_json(self,nom_liste):
        with open(os.path.join(self.dossier_listes, f"{nom_liste}.json"), "r", encoding="utf-8") as f:
            data = json.load(f)
        return data

    def get_nom_list_sel(self):
        items = self.dlg.tableWidget.selectedItems()
        if items:  # s'il y a au moins un élément sélectionné
            return items[0].text()
        return None

    def get_index_list_sel(self):
        indexes = self.dlg.tableWidget.selectedIndexes()
        if indexes:
            # index de la premiere colonne sélectionnée
            return indexes[0].row()
        return None

    def get_all_json(self):
        if os.path.exists(self.dossier_listes):
            self.fichiers_json = [f for f in os.listdir(self.dossier_listes) if f.endswith(".json")]
            return self.fichiers_json
        else:
            print("Le dossier LISTES n'existe pas")
            return {}

    def set_tablewidget_from_all_json(self):

            # on ajoute toutes les listes (json) dans le tablewidget
            for fic in self.get_all_json():
                nom_sans_ext, ext = os.path.splitext(fic)
                item_fic = QTableWidgetItem(nom_sans_ext)
                self.dlg.tableWidget.insertRow(0)
                self.dlg.tableWidget.setItem(0, 0, item_fic)

                # Charger le fichier
                with open(os.path.join(self.dossier_listes,fic), "r", encoding="utf-8") as f:
                    data = json.load(f)

                # Nombre d'éléments (clés dans le dictionnaire)
                self.nb_elements = sum(len(v) for v in data.values())
                item_nb_sel = QTableWidgetItem(str(self.nb_elements))
                # rendre non sélectionnable la 2ᵉ colonne
                item_nb_sel.setFlags(item_nb_sel.flags() & ~Qt.ItemIsSelectable)
                item_nb_sel.setTextAlignment(Qt.AlignCenter)
                self.dlg.tableWidget.setItem(0, 1, item_nb_sel)

    # créer un json vide pour chaque liste crée
    def initjsonlist(self,nom_list):
        dico_vide = {}
        fichier_json = os.path.join(self.dossier_listes, f"{nom_list}.json")
        with open(fichier_json, "w", encoding="utf-8") as f:
            json.dump(dico_vide, f, indent=2, ensure_ascii=False)

    # retourne un dictionnaire (cle = layer.name() , valeur = id des selections
    def get_dico_selection(self):
        selection_dict = {}
        # Parcours tous les layers
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == layer.VectorLayer:  # seulement les couches vecteurs
                selected_ids = layer.selectedFeatureIds()
                if selected_ids:
                    selection_dict[layer.name()] = selected_ids
        return selection_dict

    def suppr_all_list(self):
        # on vide le tablewidget
        self.dlg.tableWidget.setRowCount(0)
        # on supprime tous les json du dossier LISTES
        for f in os.listdir(self.dossier_listes):
            chemin_fichier = os.path.join(self.dossier_listes, f)
            # Supprime seulement les fichiers (évite les dossiers)
            if os.path.isfile(chemin_fichier) and f.endswith(".json"):
                os.remove(chemin_fichier)

    def suppr_list_vide(self):
        # on actualise self.fichiers_json
        for fic in self.get_all_json():
            # print(fic)
            # Charger le fichier
            with open(os.path.join(self.dossier_listes, fic), "r", encoding="utf-8") as f:
                data = json.load(f)
            # Nombre d'éléments (clés dans le dictionnaire)
            nb_elements = sum(len(v) for v in data.values())
            if nb_elements == 0:
                # on supprime le fichier
                os.remove(os.path.join(self.dossier_listes, fic))
                # on supprime la ligne du tablewidget
                nom_sans_ext,ext = os.path.splitext(fic)
                item = self.dlg.tableWidget.findItems(nom_sans_ext, Qt.MatchExactly)
                self.dlg.tableWidget.removeRow(item[0].row())

    def suppr_list_sel(self):
        items = self.dlg.tableWidget.selectedItems()
        if items:
            for item in items:
                # on supprime le fichier AVANT a ligne
                os.remove(os.path.join(self.dossier_listes, f"{item.text()}.json"))
                # supprime la ligne
                ligne = item.row()
                self.dlg.tableWidget.removeRow(ligne)


    # sélectionne toutes les entités issues de la liste sélectionnée
    def set_sel_from_list(self):
        # on désélectionne tout avant la selection de la liste
        self.deselectionne_all()

        items = self.dlg.tableWidget.selectedItems()
        if not items:
            return
        liste_sel = items[0].text()
        # lecture du json correspondant
        with open(os.path.join(self.dossier_listes, f"{liste_sel}.json"), "r", encoding="utf-8") as f:
            data = json.load(f)
            liste_ids = []
            for layer,ids in data.items():
                project = QgsProject.instance()
                layer = project.mapLayersByName(layer)
                if layer:
                    layer[0].selectByIds(ids)
                    # print(f"layer = {layer} -- ids = {ids}")

    def set_list_from_sel(self):
        selection_dict = self.get_dico_selection()
        nom_list_sel = self.get_nom_list_sel()
        fichier_json = os.path.join(os.path.dirname(__file__),"LISTES",f"{nom_list_sel}.json")
        # écriture du json
        with open(fichier_json, "w", encoding="utf-8") as f:
            json.dump(selection_dict, f, indent=2, ensure_ascii=False)

        # ecrire le nombre de selection (nb de ligne du json) dans la 2ieme colonne de la ligne sélectionnée
        nb_sel = sum(len(ids) for ids in selection_dict.values())
        item_nb = QTableWidgetItem(str(nb_sel))
        item_nb.setTextAlignment(Qt.AlignCenter)
        self.dlg.tableWidget.setItem(self.get_index_list_sel(), 1, item_nb)

    def deselectionne_all(self):
        project = QgsProject.instance()
        for layer in project.mapLayers().values():
            if isinstance(layer, QgsVectorLayer):
                layer.removeSelection()

    def double_clic_liste(self):
        self.dlg_liste.open_liste()

    def initGui(self):
        pass

    def unload(self):
        pass

    def run(self):
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = ListeDialog()


        # show the dialog
        self.dlg = ListeDialog()
        self.dlg.setWindowFlags(Qt.Window | Qt.WindowCloseButtonHint | Qt.WindowStaysOnTopHint)
        self.dlg.setWindowTitle(TITRE)

        # slot
        self.dlg.pushButtonCreerList.clicked.connect(self.creerliste)
        self.dlg.pushButtonSuppAllList.clicked.connect(self.suppr_all_list)
        self.dlg.pushButtonSupprEmptyList.clicked.connect(self.suppr_list_vide)
        self.dlg.pushButtonSupprListSel.clicked.connect(self.suppr_list_sel)
        self.dlg.pushButtonListToSelect.clicked.connect(self.set_sel_from_list)
        self.dlg.pushButtonSelectToList.clicked.connect(self.set_list_from_sel)
        # double clic dans une cellule
        self.dlg.tableWidget.cellDoubleClicked.connect(self.double_clic_liste)

        # tool = RectangleSelectAllLayers(self.iface.mapCanvas())
        # self.iface.mapCanvas().setMapTool(tool)


        self.inittablewidget()
        self.set_tablewidget_from_all_json()

        # Run the dialog event loop
        self.dlg.show()

